$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json

name: titanic-logistic-regression
version: 2
description: "Python environment for Titanic logistic regression MLOps pipeline"

image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:latest

conda_file: conda.yml

tags:
  project: titanic-logistic-regression
  team: ml-ops
